services:
  - type: web
    name: koko-roadmap
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: KOKO_ROADMAP_XLSX
        value: roadmap.xlsx
      - key: KOKO_ROADMAP_CHANGELOG
        value: changelog.csv

